spring:
  zipkin:
    base-url: http://localhost:9411
  bus:
    enabled: true
    trace:
      enabled: true
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"   