spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 
    encode: UTF-8
    timeout: 6000
    pool:
      max-active: 100
      max-wait: -1
      max-idle: 10
      min-idle: 5
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/ue189?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jamboree.springcloud.pojo